pool:
  vmImage: windows-latest

variables:
  storageAccountName: "azurek6storageaccount"
  logTableName: "loadtestresult"
  logFullTableName: "loadtestresultfull"

jobs:
- job: LoadTest
  displayName: Run Load Tests
  variables:
    - group: AzurePowershellScript
  steps:
    - task: Bash@3
      displayName: Run Load Tests
      inputs:
        targetType: 'inline'
        script: |
          echo 'Starting bash task'
          echo "SubscriptionGuid $(SubscriptionGuid)"
          echo "TenantId $(TenantId)"
