pool:
  vmImage: windows-latest

variables:
  storageAccountName: "azurek6storageaccount"
  logTableName: "loadtestresult"
  logFullTableName: "loadtestresultfull"

jobs:
- job: LoadTest
  displayName: Run Load Tests
  variables:
    - group: AzurePowershellScript
  steps:
    - task: PowerShell@2
      displayName: Run Load Tests
      inputs:
        filePath: .azuredevops/scripts/RunK6LoadTest.ps1
        arguments: '-SubscriptionGuid $(SubscriptionGuid) -TenantId $(TenantId) -ClientId $(ClientId) -ClientSecret $(ClientSecret) -storageAccountName "azurek6storageaccount" -logWorkspaceId $(logWorkspaceId) -logWorkspaceKey $(logWorkspaceKey) -logTableName "loadtestresult" -logFullTableName "loadtestresultfull"'
        pwsh: true

    - task: PowerShell@2
      displayName: Quality Gate
      inputs:
        filePath: .azuredevops/scripts/QualityLoadTest.ps1
        arguments: '-SubscriptionGuid $(SubscriptionGuid) -TenantId $(TenantId) -ClientId $(ClientId) -ClientSecret $(ClientSecret) -logWorkspaceId $(logWorkspaceId) -logWorkspaceKey $(logWorkspaceKey) -logTableName "loadtestresult" -logFullTableName "loadtestresultfull"'
        pwsh: true