pool:
  vmImage: windows-latest


parameters:
- name: DEPLOYMENT_SCRIPT
  displayName: SCRIPT_NAME
  type: string
  default: getConfiguration.js

- name: DEPLOYMENT_ENV
  displayName: DEPLOYMENT_ENV
  type: string
  default: QA
  values:
    - QA
    - TEST
    - PROD

- name: DEPLOYMENT_PROJECT
  displayName: PROJECT_NAME
  type: string
  default: Commerce

- name: DEPLOYMENT_API_NAME
  displayName: API_NAME
  type: string
  default: GetConfiguration

- name: DEPLOYMENT_USERS
  displayName: USERS
  type: string
  default: 1

- name: DEPLOYMENT_TEST_DURATION
  displayName: TEST_DURATION
  type: string
  default: 1m

- name: DEPLOYMENT_DATASOURCE
  displayName: DATASOURCE
  type: string
  default: content-services-sitecore9-custom
  values:
    - dotcom-sitecore-qa
    - dotcom-sitecore-test
    - dotcom-sitecore-prod

variables:
  storageAccountName: "azurek6storageaccount"
  logTableName: "loadtestresult"
  logFullTableName: "loadtestresultfull"

jobs:
- job: LoadTest
  displayName: Run Load Tests
  variables:
    - group: AzurePowershellScript
    - name: src_script
      value: ${{parameters.DEPLOYMENT_SCRIPT}}
    - name: src_env
      value: ${{parameters.DEPLOYMENT_ENV}}
    - name: src_project
      value: ${{parameters.DEPLOYMENT_PROJECT}}
    - name: src_api_name
      value: ${{parameters.DEPLOYMENT_API_NAME}} 
    - name: src_users
      value: ${{parameters.DEPLOYMENT_USERS}}       
    - name: src_test_duration
      value: ${{parameters.DEPLOYMENT_TEST_DURATION}}     
    - name: src_test_datasource
      value: ${{parameters.DEPLOYMENT_DATASOURCE}}    

  steps:
    - task: PowerShell@2
      displayName: Run Load Tests
      inputs:
        filePath: .azuredevops/scripts/RunK6LoadTest.ps1
        arguments: '-SubscriptionGuid $(SubscriptionGuid) -TenantId $(TenantId) -ClientId $(ClientId) -ClientSecret $(ClientSecret) -storageAccountName "azurek6storageaccount" -storageAccountKey $(storageAccountKey) -logWorkspaceId $(logWorkspaceId) -logWorkspaceKey $(logWorkspaceKey) -logTableName "loadtestresult" -logFullTableName "loadtestresultfull" -src_script $(src_script) -src_env $(src_env) -src_project $(src_project) -src_api_name $(src_api_name) -src_users $(src_users) -src_test_duration $(src_test_duration) -src_test_datasource $(src_test_datasource)'
        pwsh: true

    - task: PowerShell@2
      displayName: Quality Gate
      inputs:
        filePath: .azuredevops/scripts/QualityLoadTest.ps1
        arguments: '-SubscriptionGuid $(SubscriptionGuid) -TenantId $(TenantId) -ClientId $(ClientId) -ClientSecret $(ClientSecret) -logWorkspaceId $(logWorkspaceId) -logWorkspaceKey $(logWorkspaceKey) -logTableName "loadtestresult" -logFullTableName "loadtestresultfull"'
        pwsh: true
